# Actions 显示的名字，随意设置
name: Deploy Muxiner's Blog
# 监听到 push 事件后触发
on:
  push:
    branches:
      - source
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # 拉取当前执行 Actions 仓库的指定分支
    - name: Checkout Actions Branch
      uses: actions/checkout@v2

    # 安装 Node 环境
    - name: Setup Node Env
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"

    # 写入部署 SSH 密钥
    - name: Prepare SSH Env 
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.GH_ACTIONS }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # 配置 git 用户，用户邮箱
    - name: Prepare Git Env 
      run: |
        git config --global user.name "muxiner"
        git config --global user.email "muxinerhuang@gmail.com"

    # 安装 Hexo 依赖
    - name: Use Hexo      
      run: |
        rm -f .yarnclean
        npm ci --ignore-scripts --production=false
        rm -rf ./public
    
    # hexo clean 清除文件
    - name: Clean Public Blog Files
      run: npx hexo clean

    # hexo generate 生成静态博客文件
    - name: Generate Public Blog Files
      run: npx hexo generate

    # hexo deploy 部署博客文件
    - name: Deploy Public Blog
      run: npx hexo deploy