# Actions æ˜¾ç¤ºçš„åå­—ï¼Œéšæ„è®¾ç½®
name: Deploy Muxiner's Blog
# ç›‘å¬åˆ° push äº‹ä»¶åè§¦å‘
on:
  push:
    branches:
      - source
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # æ‹‰å–å½“å‰æ‰§è¡Œ Actions ä»“åº“çš„æŒ‡å®šåˆ†æ”¯
    - name: Checkout Actions Branch
      uses: actions/checkout@v2

    # å®‰è£… Node ç¯å¢ƒ
    - name: Setup Node Env
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"

    # å†™å…¥éƒ¨ç½² SSH å¯†é’¥
    - name: Prepare SSH Env 
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.GH_ACTIONS }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # é…ç½® git ç”¨æˆ·ï¼Œç”¨æˆ·é‚®ç®±
    - name: Prepare Git Env 
      run: |
        git config --global user.name "muxiner"
        git config --global user.email "muxinerhuang@gmail.com"

    # å®‰è£… Hexo ä¾èµ–
    - name: Use Hexo      
      run: |
        rm -f .yarnclean
        npm ci --ignore-scripts --production=false
        rm -rf ./public
    
    # hexo clean æ¸…é™¤æ–‡ä»¶
    - name: Clean Public Blog Files
      run: npx hexo clean

    # hexo generate ç”Ÿæˆé™æ€åšå®¢æ–‡ä»¶
    - name: Generate Public Blog Files
      run: | 
        npx hexo generate
        ls -al
        pwd

    # hexo deploy éƒ¨ç½²åšå®¢æ–‡ä»¶
    - name: Deploy Public Blog
      run: | 
        # npx hexo deploy
        git add -f public/
        git commit -m "ğŸ˜go to master"
        git push --force --quiet source:master
        